str = 'ATGACAAGATGCCATTGTCCCCCGGCCTCCTGCTGCTGCTGCTCTCCGGGGCCACGGCCACCGCTGCCCTGCC'\
'CCTGGAGGGTGGCCCCACCGGCCGAGACAGCGAGCATATGCAGGAAGCGGCAGGAATAAGGAAAAGCAGC'\
'CTCCTGACTTTCCTCGCTTGGTGGTTTGAGTGGACCTCCCAGGCCAGTGCCGGGCCCCTCATAGGAGAGG'\
'AAGCTCGGGAGGTGGCCAGGCGGCAGGAAGGCGCACCCCCCCAGCAATCCGCGCGCCGGGACAGAATGCC'\
'CTGCAGGAACTTCTTCTGGAAGACCTTCTCCTCCTGCAAATAAAACCTCACCCATGAATGCTCACGCAAG'\
'TTTAATTACAGACCTGAA'

atg = 'ATG'
tag = 'TAG'
tta = 'TTA'
tga = 'TGA'

print('Aantal atg: ', str.count(atg))
print('Aantal tag: ', str.count(tag))
print('Aantal tta: ', str.count(tta))
print('Aantal tga: ', str.count(tga))
